import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Flex, Heading, Link, Icon, Text, Avatar } from '@chakra-ui/react'
import { FiBox, FiDollarSign, FiHome, FiPieChart } from 'react-icons/fi';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard Next js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        h="100vh"
        flexDir="row"
        overflow="hidden"
        maxW="2000px"
      >
        {/* Column 1 */}
        <Flex
          w="15%"
          flexDir="column"
          alignItems="center"
          background="#020202"
          color="#fff"
        >
          <Flex
            flexDir="column"
            justifyContent="space-between"
            height='100vh'
          >
            <Flex flexDir="column" as="nav">
              <Heading
                mt={50} mb={100}
                fontSize="4xl"
                alignSelf="center"
                laterSpacing="tight"
              >
                Rise.
              </Heading>
              <Flex flexDir="column" align="flex-start" justify="center">
                <Flex align="center" className='sidebar-items' color='gray' fontSize="2xl" mb='5'>
                  <Link>
                    <Icon as={FiHome} fontSize="2xl" className='active-icon'/>
                  </Link>
                  <Link _hover={{ textDecor: 'none' }}>
                    <Text className='active' ms='3'>Home</Text>
                  </Link>
                </Flex>
                <Flex align="center" className='sidebar-items' color='gray' fontSize="2xl" mb='5'>
                  <Link>
                    <Icon as={FiPieChart} fontSize="2xl" />
                  </Link>
                  <Link _hover={{ textDecor: 'none' }}>
                    <Text ms='3'>Wallet</Text>
                  </Link>
                </Flex>
                <Flex align="center" className='sidebar-items' color='gray' fontSize="2xl" mb='5'>
                  <Link>
                    <Icon as={FiDollarSign} fontSize="2xl" />
                  </Link>
                  <Link _hover={{ textDecor: 'none' }}>
                    <Text ms='3'>Credit</Text>
                  </Link>
                </Flex>
                <Flex align="center" className='sidebar-items' color='gray' fontSize="2xl" mb='5'>
                  <Link>
                    <Icon as={FiBox} fontSize="2xl" />
                  </Link>
                  <Link _hover={{ textDecor: 'none' }}>
                    <Text ms='3'>Services</Text>
                  </Link>
                </Flex>
              </Flex>
            </Flex>

            <Flex flexDir='column' alignItems="center" mb={10} mt={5}>
              <Avatar my={2} src='logo.png'/>
              <Text textAlign="center">Calvin West</Text>
            </Flex>

          </Flex>

        </Flex>


        {/* Column 2 */}
        <Flex>

        </Flex>


        {/* Column 3 */}
        <Flex>

        </Flex>

      </Flex>
    </>
  )
}
